influxdb:
  build: ./influxdb
  ports: 
  - "8083:8083"
  - "8084:8084"
  - "8086:8086"
  environment:
  - PRE_CREATE_DB=cf_np;cf_prd;bosh_np;bosh_prd
heka:
  build: ./heka
  ports: 
  - "2003:2003"
  - "2004:2004"
  - "8500:8500"
  - "4352:4352"
  - "5565:5565"
  volumes:
  - ./heka/hekad.toml:/etc/hekad/hekad.toml
  links:
  - influxdb
grafana:
  image: grafana/grafana:latest 
  ports:
  - "3000:3000"
  volumes:
  - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
  links: 
  - influxdb 
